export const GameTournaments = {
  WorldCup2018: {
      name: "World Cup 2018",
      matchStages: [
        //Groupstage match day1
        {
          StartMatchNumber: 1,
          EndMatchNumber: 16,
          Desc: 'MATCHDAY ONE',
          StageStartDate: 'June 14, 2018',
          StageEndDate: 'June 19, 2018',
          Stage: 1,
          ScoreAndWinnerPoints: 3,
          WinnerOnlyPoints: 1,
          LostPoints: 0
        },
        //Groupstage match day2
        {
          StartMatchNumber: 17,
          EndMatchNumber: 32,
          Desc: 'MATCHDAY TWO',
          StageStartDate: 'June 19, 2018',
          StageEndDate: 'June 24, 2018',
          Stage: 2,
          ScoreAndWinnerPoints: 3,
          WinnerOnlyPoints: 1,
          LostPoints: 0
        },
        //Groupstage match day3
        {
          StartMatchNumber: 33,
          EndMatchNumber: 48,
          Desc: 'MATCHDAY THREE',
          StageStartDate: 'June 25, 2018',
          StageEndDate: 'June 28, 2018',
          Stage: 3,
          ScoreAndWinnerPoints: 3,
          WinnerOnlyPoints: 1,
          LostPoints: 0
        },
        //round 16
        {
          StartMatchNumber: 49,
          EndMatchNumber: 56,
          Desc: 'ROUND OF 16',
          StageStartDate: 'June 30, 2018',
          StageEndDate: 'July 3, 2018',
          Stage: 4,
          ScoreAndWinnerPoints: 3,
          WinnerOnlyPoints: 1,
          LostPoints: 0
        },
        //quarter finals
        {
          StartMatchNumber: 57,
          EndMatchNumber: 60,
          Desc: 'QUARTER-FINALS',
          StageStartDate: 'July 6, 2018',
          StageEndDate: 'July 7, 2018',
          Stage: 5,
          ScoreAndWinnerPoints: 5,
          WinnerOnlyPoints: 3,
          LostPoints: -1
        },
        //semi finals
        {
          StartMatchNumber: 61,
          EndMatchNumber: 62,
          Desc: 'SEMI-FINALS',
          StageStartDate: 'July 10, 2018',
          StageEndDate: 'July 12, 2018',
          Stage: 6,
          ScoreAndWinnerPoints: 15,
          WinnerOnlyPoints: 5,
          LostPoints: -5
        },
        //loser finals
        {
          StartMatchNumber: 63,
          EndMatchNumber: 63,
          Desc: 'THIRD-PLACE',
          StageStartDate: 'July 14, 2018',
          StageEndDate: 'July 14, 2018',
          Stage: 7,
          ScoreAndWinnerPoints: 40,
          WinnerOnlyPoints: 15,
          LostPoints: -10,
          IsFinal: 'True'
        },
        //winner & loser finals
        {
          StartMatchNumber: 64,
          EndMatchNumber: 64,
          Desc: 'FINAL',
          StageStartDate: 'July 15, 2018',
          StageEndDate: 'July 15, 2018',
          Stage: 8,
          ScoreAndWinnerPoints: 40,
          WinnerOnlyPoints: 15,
          LostPoints: -10,
          IsFinal: 'True'
        }
      ],
  },
  EuroCup2020: {
      name: "Euro Cup 2020",
      matchStages: [
        {
          //stage1
          StartMatchNumber: 1,
          EndMatchNumber: 36,
          Desc: 'GROUP-STAGE',
          StageStartDate: 'June 11, 2021',
          StageEndDate: 'June 23, 2021',
          Stage: 0,
          ScoreAndWinnerPoints: 3,
          WinnerOnlyPoints: 1,
          LostPoints: 0
        },
        {
          //round of 16
          StartMatchNumber: 37,
          EndMatchNumber: 44,
          Desc: 'ROUND OF 16',
          StageStartDate: 'June 26, 2021',
          StageEndDate: 'June 30, 2021',
          Stage: 1,
          ScoreAndWinnerPoints: 3,
          WinnerOnlyPoints: 1,
          LostPoints: 0
        },
        {
          //quarter-finals
          StartMatchNumber: 45,
          EndMatchNumber: 48,
          Desc: 'QUARTER-FINALS',
          StageStartDate: 'July 2, 2021',
          StageEndDate: 'July 4, 2021',
          Stage: 2,
          ScoreAndWinnerPoints: 5,
          WinnerOnlyPoints: 3,
          LostPoints: -1
        },
        {
          //semi-finals
          StartMatchNumber: 49,
          EndMatchNumber: 50,
          Desc: 'SEMI-FINALS',
          StageStartDate: 'July 7, 2021',
          StageEndDate: 'July 8, 2021',
          Stage: 3,
          ScoreAndWinnerPoints: 15,
          WinnerOnlyPoints: 5,
          LostPoints: -5
        },
        {
          //finals
          StartMatchNumber: 51,
          EndMatchNumber: 51,
          Desc: 'FINALS',
          StageStartDate: 'July 12, 2021',
          StageEndDate: 'July 12, 2021',
          Stage: 4,
          ScoreAndWinnerPoints: 40,
          WinnerOnlyPoints: 15,
          LostPoints: -10,
          IsFinal: 'True'
        }
      ],
  },
  WorldCup2022: {
      name: "World Cup 2022",
      matchStages: [
        //Groupstage match day1
        {
          StartMatchNumber: 1,
          EndMatchNumber: 16,
          Desc: 'MATCHDAY ONE',
          StageStartDate: 'November 21, 2022',
          StageEndDate: 'November 24, 2022',
          Stage: 1,
          ScoreAndWinnerPoints: 3,
          WinnerOnlyPoints: 1,
          LostPoints: 0
        },
        //Groupstage match day2
        {
          StartMatchNumber: 17,
          EndMatchNumber: 32,
          Desc: 'MATCHDAY TWO',
          StageStartDate: 'November 25, 2022',
          StageEndDate: 'November 28, 2022',
          Stage: 2,
          ScoreAndWinnerPoints: 3,
          WinnerOnlyPoints: 1,
          LostPoints: 0
        },
        //Groupstage match day3
        {
          StartMatchNumber: 33,
          EndMatchNumber: 48,
          Desc: 'MATCHDAY THREE',
          StageStartDate: 'November 29, 2022',
          StageEndDate: 'December 2, 2022',
          Stage: 3,
          ScoreAndWinnerPoints: 3,
          WinnerOnlyPoints: 1,
          LostPoints: 0
        },
        //round 16
        {
          StartMatchNumber: 49,
          EndMatchNumber: 56,
          Desc: 'ROUND OF 16',
          StageStartDate: 'December 3, 2022',
          StageEndDate: 'December 6, 2022',
          Stage: 4,
          ScoreAndWinnerPoints: 3,
          WinnerOnlyPoints: 1,
          LostPoints: 0
        },
        //quarter finals
        {
          StartMatchNumber: 57,
          EndMatchNumber: 60,
          Desc: 'QUARTER-FINALS',
          StageStartDate: 'December 9, 2022',
          StageEndDate: 'December 10, 2022',
          Stage: 5,
          ScoreAndWinnerPoints: 5,
          WinnerOnlyPoints: 3,
          LostPoints: -1
        },
        //semi finals
        {
          StartMatchNumber: 61,
          EndMatchNumber: 62,
          Desc: 'SEMI-FINALS',
          StageStartDate: 'December 13, 2022',
          StageEndDate: 'December 14, 2022',
          Stage: 6,
          ScoreAndWinnerPoints: 15,
          WinnerOnlyPoints: 5,
          LostPoints: -5
        },
        //loser finals
        {
          StartMatchNumber: 63,
          EndMatchNumber: 63,
          Desc: 'THIRD-PLACE',
          StageStartDate: 'December 17, 2022',
          StageEndDate: 'December 17, 2022',
          Stage: 7,
          ScoreAndWinnerPoints: 40,
          WinnerOnlyPoints: 15,
          LostPoints: -10,
          IsFinal: 'True'
        },
        //finals
        {
          StartMatchNumber: 64,
          EndMatchNumber: 64,
          Desc: 'FINAL',
          StageStartDate: 'December 18, 2022',
          StageEndDate: 'December 18, 2022',
          Stage: 8,
          ScoreAndWinnerPoints: 40,
          WinnerOnlyPoints: 15,
          LostPoints: -10,
          IsFinal: 'True'
        }
      ],
  }
}

export const teamNameAcronymn = {
  'Argentina': 'ARG',
  'Australia': 'AUS',
  'Austria': 'AUT',
  'Belgium': 'BEL',
  'Brazil': 'BRA',
  'Cameroon': 'CMR',
  'Canada': 'CAN',
  'Colombia': 'COL',
  'Costa Rica': 'CRC',
  'Croatia': 'CRO',
  'Czech Republic': 'CZE',
  'Denmark': 'DEN',
  'Egypt': 'EGY',
  'England': 'ENG',
  'Ecuador': 'ECU',
  'France': 'FRA',
  'Finland': 'FIN',
  'Ghana': 'GHA',
  'Germany': 'GER',
  'Hungary': 'HUN',
  'Iceland': 'ISL',
  'Iran': 'IRN',
  'Italy': 'ITA',
  'Japan': 'JPN',
  'Korea Republic': 'KOR',
  'South Korea': 'KOR',
  'Mexico': 'MEX',
  'Morocco': 'MAR',
  'Nigeria': 'NGA',
  'Netherlands': 'NED',
  'North Macedonia': 'MKD',
  'Panama': 'PAN',
  'Peru': 'PER',
  'Poland': 'POL',
  'Portugal': 'POR',
  'Qatar': 'QAT',
  'Russia': 'RUS',
  'Saudi Arabia': 'KSA',
  'Scotland': 'SCO',
  'Senegal': 'SEN',
  'Serbia': 'SRB',
  'Spain': 'ESP',
  'Sweden': 'SWE',
  'Slovakia': 'SVK',
  'Switzerland': 'SUI',
  'Tunisia': 'TUN',
  'Turkey': 'TUR',
  'Uruguay': 'URU',
  'Ukraine': 'UKR',
  'Wales': 'WAL',
  'United States': 'USA',
  'TBD': 'TBD',
}

//Look at the folder /img/country-flags-main/* 
//for the SVG name
export var team2LetterAcronym = {
  'Argentina': 'ar',
  'Australia': 'au',
  'Austria': 'at',
  'Belgium': 'be',
  'Brazil': 'br',
  'Cameroon': 'cm',
  'Canada': 'ca',
  'Colombia': 'co',
  'Costa Rica': 'cr',
  'Croatia': 'hr',
  'Czech Republic': 'cz',
  'Denmark': 'dk',
  'Ecuador': 'ec',
  'Egypt': 'eg',
  'England': 'gb',
  'France': 'fr',
  'Finland': 'fi',
  'Ghana': 'gh',
  'Germany': 'de',
  'Hungary': 'hu',
  'Iceland': 'is',
  'Iran': 'ir',
  'Italy': 'it',
  'Japan': 'jp',
  'Korea Republic': 'kp',
  'South Korea': 'kr',
  'Mexico': 'mx',
  'Morocco': 'ma',
  'Nigeria': 'ng',
  'Netherlands': 'nl',
  'North Macedonia': 'mk',
  'Panama': 'pa',
  'Peru': 'pe',
  'Poland': 'pl',
  'Portugal': 'pt',
  'Qatar': 'qa',
  'Russia': 'ru',
  'Saudi Arabia': 'sa',
  'Scotland': 'gb-sct',
  'Senegal': 'sn',
  'Serbia': 'rs',
  'Spain': 'es',
  'Sweden': 'se',
  'Slovakia': 'sk',
  'Switzerland': 'ch',
  'Tunisia': 'tn',
  'Turkey': 'tr',
  'Uruguay': 'uy',
  'Ukraine': 'ua',
  'Wales': 'gb-wls',
  'United States': 'us',
}

export const team3To2LetterAcronym = {
  'ARG':'ar',
  'AUS':'au',
  'AUT':'at',
  'BEL':'be',
  'BRA':'br',
  'CMR':'cr',
  'CAN':'ca',
  'COL':'co',
  'CRC':'cr',
  'CRO':'hr',
  'CZE':'cz',
  'DEN':'dk',
  'EGY':'ec',
  'ENG':'eg',
  'ECU':'gb',
  'FRA':'fr',
  'FIN':'fi',
  'GHA':'gh',
  'GER':'de',
  'HUN':'hu',
  'ISL':'is',
  'IRN':'ir',
  'ITA':'it',
  'JPN':'jp',
  'KOR':'kr',
  'MEX':'mx',
  'MAR':'ma',
  'NGA':'ng',
  'NED':'nl',
  'MKD':'mk',
  'PAN':'pa',
  'PER':'pe',
  'POL':'pl',
  'POR':'pt',
  'QAT':'qa',
  'RUS':'ru',
  'KSA':'sa',
  'SCO':'gb-sct',
  'SEN':'sn',
  'SRB':'rs',
  'ESP':'es',
  'SWE':'se',
  'SVK':'sk',
  'SUI':'ch',
  'TUN':'tn',
  'TUR':'tr',
  'URU':'uy',
  'UKR':'ua',
  'WAL':'gb-wls',
  'USA':'us',
  'TBD':'TBD',
}